# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def defaultPods 
  use_frameworks!
  inhibit_all_warnings!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya/RxSwift'
  pod 'Kingfisher'
  pod 'Cosmos'
  #pod 'SwiftLint'
end

def testPods
  use_frameworks!
  inhibit_all_warnings!
 pod 'Quick'
 pod 'Nimble'
end

target 'github-challenge' do 
  defaultPods
end

target 'github-challengeTests' do 
  testPods
end

#target 'github-challenge' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for github-challenge

#  target 'github-challengeTests' do
#    inherit! :search_paths
    # Pods for testing
#  end

#end
